<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5EKQJAd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5EKQJAd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5EKQJAd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5EKQJAd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5EKQJAd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5EKQJAd',
    'container.build_id' => '8c33b5f9',
    'container.build_time' => 1574992889,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5EKQJAd');
