<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container7yn3SUO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7yn3SUO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7yn3SUO.legacy');
=======
if (\class_exists(\ContainerBDxa6r8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBDxa6r8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBDxa6r8.legacy');
>>>>>>> 8a245b8a93875077fb00da5a98dd53b40aa9999e

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container7yn3SUO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7yn3SUO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7yn3SUO',
    'container.build_id' => 'a777e595',
    'container.build_time' => 1574984368,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7yn3SUO');
=======
    \class_alias(\ContainerBDxa6r8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBDxa6r8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BDxa6r8',
    'container.build_id' => '07f1e788',
    'container.build_time' => 1574957388,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBDxa6r8');
>>>>>>> 8a245b8a93875077fb00da5a98dd53b40aa9999e
